services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mysql:
    image: mysql:8.0
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  stock-api:
    build:
      context: ./stock-api
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./stock-api:/var/www/html
    depends_on:
      - rabbitmq
      - mysql
    environment:
      SERVICE_NAME: stock-api
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: stockdb

  log-api:
    build:
      context: ./log-api
      dockerfile: Dockerfile
    ports:
      - 8002:80
    volumes:
      - ./log-api:/var/www/html
    depends_on:
      - rabbitmq
      - mongo
    environment:
      SERVICE_NAME: log-api
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongo

volumes:
  mysql_data:
